### ISSUE TITLE
Add zero counts for bee (and possibly other data)

### ISSUE THREAD

**Issue by jarad** [jarad/ISUmonarch#1]
Many of the bee data have zero counts. We need to make sure that these show up in a future data set.

**Comment by jarad** [comment]
We could include this as part of either a vignette or as examples in the helpfiles for each data type. Actually I'm thinking maybe we want this as a vignette.

**Comment by nulloa** [comment]
I've created a vignette for the bee data. Let me know if you are looking for anything more specific.

**Comment by nulloa** [comment]
Also in order to build the vignettes when you download the files you need to run this command:
```
devtools::install(build_vignettes = TRUE)
```

**Comment by jarad** [comment]
If a survey had no bee information at all, would those surveys get zeros? I feel like the current code will only fill zeros for surveys that had at least 1 observation. I think we need to complete using the `survey` data.frame.

**Comment by nulloa** [comment]
Ok this should be good now.

**Comment by jarad** [comment]
The zeros probably need to be added earlier, i.e. when the R data.frame is built. If this is not done, then users of the R package will probably use the data.frames incorrectly. But, this becomes a chicken-and-egg situation where we need the `survey` data.frame in order to construct other data.frames, e.g. the bee data.frame.

**Comment by jarad** [comment]
Rather than using the `survey` data.frame, use the existence of a file to indicate that a survey was done.

**Comment by jarad** [comment]
This was fixed for bee in commit 91916f24f19b. It should be fixed for other data in the process of addressing #96.
