### ISSUE TITLE
Parsing failures when running environment.R

### ISSUE THREAD

**Issue by jarad** [jarad/ISUmonarch#16]
Running [environment.R](https://github.com/jarad/ISUmonarch/blob/master/data-raw/environment.R) from the data-raw/ directory has parsing failures.

**Comment by sethapp** [comment]
I'm not sure what I should be seeing here or what I should be fixing. When I run the code I'm fine until I reach the code:
  select(-environment, -extension) %>%
  tidyr::spread(variable, value)

Then I get this:
+ environment <- read_dir(path = "environment",
+                pattern = "*.csv",
+                into = c("environment",
+                         "year","month","day","recorder",
+                         "site","transect","round",
+                         "extension")) %>%
+   select(-environment, -extension) %>%
+   tidyr::spread(variable, value)
Error in -environment : invalid argument to unary operator

**Comment by jarad** [comment]
This doesn't happen for me. Can you make sure you are running all the code and running from the data-raw/ directory?

**Comment by sethapp** [comment]
I got it figured out. The grad students in the office helped me troubleshoot it. I'll start fixing the files now

**Comment by sethapp** [comment]
Sometimes more than 1 'dominant species' were present at a site which is the final line in each file. This was expected. The two or three species should have been separated by a semi colon but a comma was used instead...adding an extra 1-2 columns

**Comment by sethapp** [comment]
This issue is closed if this warning message doesn't mean anything:
Warning message:
In evalq(as.numeric(milkweed_ramet), <environment>) :
  NAs introduced by coercion
> 
> devtools::use_data(environment,
+                    overwrite = TRUE)
Saving environment as environment.rda to C:/Users/sethapp/Documents/Git/ISUmonarch/data
>

**Comment by jarad** [comment]
This was caused by an "na" in [prd1_tprd1a_3.csv](https://github.com/jarad/ISUmonarch/blob/master/data-raw/environment/2017/08/11/NickO/prd1_tprd1a_3.csv). I fixed this in 491d26cdc by replacing the "na" with 0. If it should really be missing, then we should delete the 0 and leave it blank. If replacing the "na" with 0 is appropriate, then you can close this issue. Otherwise, make the appropriate fix and close.
