### ISSUE TITLE
Bee data column names: Pollinator Species vs Bee Species

### ISSUE THREAD

**Issue by jarad** [jarad/ISUmonarch#18]
Currently most of the bee data uses "Pollinator Species" but some uses "Bee Species". These are the files that use "Bee Species" rather than "Pollinator Species":

  Nectar Plant Species Pollinator Species year month day recorder site transect round
171       canada thistle               <NA> 2017    06  15    KoalC uth2   tuth2a     1
172       canada thistle               <NA> 2017    06  15    KoalC uth2   tuth2a     1
173        partridge pea               <NA> 2017    07  13    AlecE byd1   tbyd1a     2
174        partridge pea               <NA> 2017    07  13    AlecE byd1   tbyd1a     2
175         white clover               <NA> 2017    07  14    KoalC cra1   tcra1a     2
176           red clover               <NA> 2017    07  14    KoalC cra1   tcra1a     2
177     black eyed susan               <NA> 2017    07  14    KoalC cra1   tcra1a     2
178         white clover               <NA> 2017    07  14    KoalC cra1   tcra1a     2
179        partridge pea               <NA> 2017    08  14    AlecE uth1   tuth1a     3
180       canada thistle               <NA> 2017    08  14    AlecE uth1   tuth1a     3
181            smartweed               <NA> 2017    08  30   RoyceB cra1   tcra1a     3
182         white clover               <NA> 2017    08  30   RoyceB cra1   tcra1a     3

Currently bee.R deals with this via 

    # Some data files used Bee Species and others used Pollinator Species
      mutate(pollinator = ifelse(is.na(`Bee Species`), 
                           `Pollinator Species`,
                             `Bee Species`)) %>%

**Comment by sethapp** [comment]
"Pollinator Species" is the old header which is only on 2016 round 1 physical data sheets but it appears this header continued to be used for all 2016 data sheets and even into 2017. All 2016 round 2 and 3 entries should say "Bee Species" as well as all of 2017 data.
