### ISSUE TITLE
Nectar species names in a single file

### ISSUE THREAD

**Issue by jarad** [jarad/ISUmonarch#19]
Currently there are two files in data-raw/nectar/ that are both meant to relate common names to scientific names and other information. We should have only 1 and it should not have a csv extension so as to not interfere with the data-raw/nectar.R script.

**Comment by sethapp** [comment]
I deleted the old files (which were outdated) and uploaded a new one as a txt file. The new text file doesn't have "" around every data piece like the old files did. Is that a problem? I couldn't figure out how to save as a text file and include the ""

**Comment by jarad** [comment]
No, not a problem. I believe those came because I read a previous version of the file into R and then wrote it out with the default that includes quotes.
