### ISSUE TITLE
Sort species by native/planted

### ISSUE THREAD

**Issue by jarad** [jarad/ISUmonarch#25]
In the NCIG report, sort species by whether they are native and whether they were planted.

**Comment by sethapp** [comment]
When these are sorted for the nectar data I believe this is how I want them sorted:
-Planted species (all are native)
-Non planted species
     ----Introduced
     ----Native
     ----Both

**Comment by sethapp** [comment]
Moved issue to ISUmonarch_figuresAndTables directory
