### ISSUE TITLE
Combine robel and daubenmire folders

### ISSUE THREAD

**Issue by jarad** [jarad/ISUmonarch#3]
I believe we decided to combine the robel and daubenmire folders into a single folder. Currently we should call this daubenmire and we'll change the name later. So the files in the data-raw/robel folder needs to be moved to data-raw/daubenmire.

**Comment by jarad** [comment]
I don't believe the push did what should have been done. Previously the folder data-raw/robel/ contained some csv files. These files should have been **moved** into data-raw/daubenmire/. Instead, I believe these folders were copied into data-raw/daubenmire/robel/. Is that true? If so, we should 

1. Move the files from data-raw/daubenmire/robel into data-raw/daubenmire/, i.e. eliminating the robel/ subdirectory.
2. Remove the files from data-raw/robel/

**Comment by chaggard7** [comment]
Okay, it should be updated now so that each "data-raw/daubenmire/2016/MM/DD/Observer" folder contains .csv files for daubenmire and .csv2 files for robel.
