### ISSUE TITLE
Create data-raw/survey.R

### ISSUE THREAD

**Issue by jarad** [jarad/ISUmonarch#33]
The [run-all.R](https://github.com/jarad/ISUmonarch/blob/master/data-raw/run_all.R) script indicates there should be a file called `length.R` to extract the transect lengths, but this file does exist and therefore needs to be created. For now the `length.R` line in `run-all.R` is commented out.

**Comment by nulloa** [comment]
Just a note that length.R was renamed to survey.R

**Comment by nulloa** [comment]
@sethapp and @jarad,

I have created this R script, but I'm not sure what we want to keep or remove. We can talk more in our meeting but currently the variables in the new `survey` dataset are:
```
 [1] "siteID"                           "transectID"                       "site_name"                       
 [4] "grant"                            "round1"                           "round2"                          
 [7] "round3"                           "length"                           "r1_date"                         
[10] "r2_date"                          "r3_date"                          "r3_date_monarch_resample"        
[13] "total_#_rounds"                   "area_m2"                          "acres"                           
[16] "r1_section_length"                "r2_section_length"                "r3_section_length"               
[19] "r1_monarch_time"                  "r2_monarch_time"                  "r3_monarch_time"                 
[22] "year"                             "r3_date_bee/environment_resample"
```

Some of the variables are year specific, but in general the first 8 and `year` are there for all the years.

**Comment by jarad** [comment]
Let's restructure this data.frame and raw data files so that each row is a survey that includes the following columns: transectID, year, round, length (transect length for that round), section_length, area, and monarch_time.

**Comment by nulloa** [comment]
Ok, @sethapp the new csvs are in the folders labeled `survey2016.csv`, etc... I removed the observations that had `NA` in the variables: `length`, `section_length`, `monarch_time`.

Let me know if I missed anything or if there are surveys missing that should be there. For instance, I'm not sure if you want to allow `NA`s in any of the above variables. If so, just let me know and I'll change it.

**Comment by sethapp** [comment]
survey2016.csv
Removing observations which are NA for length makes sense as there is no observation if length is NA. If a length exists we should retain NA for section length and monarch time. This simply means the section length or monarch time is unknown because it wasn't recorded. with these changes round 1 should have 37 total lines I believe 

survey2017.csv and survey2018.csv are blank other than the header is present

@nulloa

**Comment by nulloa** [comment]
@sethapp Yup because of the NA's the other two were blank. Should be all fixed now. 2016 was showing the correct amount of lines. Let me know if there's anything else wrong.

**Comment by sethapp** [comment]
@nulloa The number of lines (# of surveys) are correct for all years. Although data was not recorded in a column the 'section_length' for 2017, 2018 was always 10 (and will remain 10 in 2019). The same concept is true for 'monarch_time'; for 2017, 2018 it was always 20. Should I add the information manually to the csv?

**Comment by nulloa** [comment]
Ok so I've added the values for `section_length` and `monarch_time` for 2017 and 2018, and I removed `siteID` from the data.frame since I created the transect data.frame.

Can you check if these files are alright @sethapp

**Comment by nulloa** [comment]
Once you approve, we can delete the old csv files and just use the new csv files. Also, I've commented `source(survey.R)` out of `run_all.R` since once we delete the old files this current script will not be relevant anymore.

**Comment by sethapp** [comment]
Files are correct. Once you do the steps you mentioned in your previous comment I think you can close this issue @nulloa
