### ISSUE TITLE
CSV doesn't match PDF

### ISSUE THREAD

**Issue by handelj** [jarad/ISUmonarch#34]
https://github.com/jarad/ISUmonarch/blob/master/data-raw/bee/2016/06/28/KelseyFJohnP/byd2_tbyd2a_1.csv

https://github.com/jarad/ISUmonarch/blob/master/data-raw/bee/2016/06/28/KelseyFJohnP/byd2_tbyd2a_1.PDF

**Comment by jarad** [comment]
I suggest Jacob just make the fixes and commit them. If we want to create a github issue, then it would be good to have a note about what is different. I believe the "sky" is mostly_clear and it should be mostly_sunny, but it took me a while to figure this out.

**Comment by sethapp** [comment]
Deleted wrong PDF, added correct PDF.

Jacob fixes it if he knows what went wrong. If he doesn't know he makes an issue and I resolve it.
