### ISSUE TITLE
CSV donesn't match PDF

### ISSUE THREAD

**Issue by handelj** [jarad/ISUmonarch#35]
https://github.com/jarad/ISUmonarch/blob/master/data-raw/bee/2016/07/25/KelseyF/cra1_tcra1a_2.PDF

https://github.com/jarad/ISUmonarch/blob/master/data-raw/bee/2016/07/25/KelseyF/cra1_tcra1a_2.csv

**Comment by sethapp** [comment]
Deleted wrong PDF, added correct PDF
