### ISSUE TITLE
Recorder should be Observer in all .R files

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch#36]
all .R files use the variable  'recorder' in the script but the variable should be 'observer'. All data entry file names are built on who the observer is, not the recorder. Data sheets from 2016 do not differentiate observer from recorder but all 2017-2018 data sheets do. Nothing is 'wrong' with the script (I think); it's just that the incorrect noun is confusing.

**Comment by sethapp** [comment]
It looks like 'observer' was removed from all .R help files except landscape. If I recall, we want to retain observer. It looks like 'recorder' was deleted instead of being replaced by 'observer'.  
@jarad @nulloa

**Comment by nulloa** [comment]
@sethapp It looks like in landscape, `observer` was still there. Is this correct?

```
> head(landscape2016)
  year month day siteID transectID round direction milkweed flowering_plants    observer
1 2016    06  27   van2     tvan2a     1   general      yes              yes BobHBrookeH
2 2016    06  27   fis1     tfis1a     1   general      yes              yes     KelseyF
3 2016    06  27   jon1     tjon1a     1   general      yes              yes     KelseyF
4 2016    06  27   nie1     tnie1a     1   general      yes               no     KelseyF
5 2016    06  27   vos1     tvos1a     1   general      yes              yes     KelseyF
6 2016    06  27   har1     thar1a     1   general      yes              yes     SydneyH
```

**Comment by jarad** [comment]
Include observer in all R data.frames
