### ISSUE TITLE
Daubenmire variables

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch#38]
https://github.com/jarad/ISUmonarch/blob/master/R/daubenmire.R

I'm not sure what 'land_cover' and 'percentage' mean. I'm assuming land cover tells us whether it's CSG, WSG, forbs... etc. and 'percentage' simply tells us that this number is a %, one of the daubenmire coverage class numbers. 

I'm a little surprised the names(daubenmire) text didn't kick out anything like 'count' for the milkweed count data for the three different species. Or something like 'depth' to indicate that the last column is depth in cm of litter.

**Comment by jarad** [comment]
I'm happy to make the script produce whatever you want it to produce. Currently the following lines just collapse everything to the `land_cover` and `percentage` variables, but clearly this is not what is desired.

      gather(land_cover, percentage,
         -section, 
         -year, -month, -day, 
         -recorder, -siteID, -transectID, -round,
         na.rm = TRUE) %>%

If the data are truly different, e.g. counts for some species and percentage for others, then we may want to split the data set into two (or more) data sets according to the type of data. Let me know what makes sense.

**Comment by sethapp** [comment]
If I understand how variables work I think the variables should be 
'land_cover_percentage' 
'milkweed_ramet'*
'litter_depth'** (or maybe just 'depth')

These three variables all have different units. %, count, and depth in cm respectively. All data is taken over the same area; 0.5m2.

Using the data header below I have indicated which columns relate to each of the three variables using no mark or *'s. 

"section",csg,wsg,forbs,milkweed,common_ramet*,swamp_ramet*,butterfly_ramet*,woody_species,bare_ground,leaf_litter,litter_depth**

**Comment by jarad** [comment]
Need to create 3 data.frames: cover, milkweed, litter

all three data.frames have these variables: year, month, day, siteID, transectID, round, section

cover has two new variables: class and percentage
milkweed has two new variables: milkweed_species and ramets
litter has one new column: depth

**Comment by nulloa** [comment]
Done. Closed with 2bbd468aae6e0510315032113e0702258dc8c5d3

**Comment by nulloa** [comment]
@sethapp Do you want to a look at this? Check if they are correct?

**Comment by sethapp** [comment]
@nulloa  From what I can tell cover, milkweed, and litter all look correct.
