### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by handelj** [jarad/ISUmonarch#40]
Missing both pre3b_tpre3b_1.cvs and pre3b_tpre3b_1.cvs2

https://github.com/jarad/ISUmonarch/blob/master/data-raw/daubenmire/2018/06/18/WillDNancyS/pre3b_tpre3b_1.pdf

**Comment by sethapp** [comment]
No missing data. PDF was in wrong folder. Deleted PDF. Correct PDF, csv and csv2 is in 'Nancy' folder.
