### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by handelj** [jarad/ISUmonarch#41]
Missing both pre4b_tpre4b_1.csv and pre4b_tpre4b_1.csv2

https://github.com/jarad/ISUmonarch/blob/master/data-raw/daubenmire/2018/06/18/WillDNancyS/pre4b_tpre4b_1.pdf

**Comment by sethapp** [comment]
From what I can see these files are not missing. Can you see them? Did you mean to reference a different entry?

**Comment by jarad** [comment]
https://github.com/jarad/ISUmonarch/blob/master/data-raw/daubenmire/2018/06/18/WillDNancyS/pre4b_tpre4b_1.csv
https://github.com/jarad/ISUmonarch/blob/master/data-raw/daubenmire/2018/06/18/WillDNancyS/pre4b_tpre4b_1.csv2

**Comment by handelj** [comment]
I see them now, but I could have sworn they weren't there earlier. Thanks!
