### ISSUE TITLE
2017 bee data has a Start Time row that needs to be delt with

### ISSUE THREAD

**Issue by jarad** [jarad/ISUmonarch#5]
Bee data from 2017 has an additional row compared to the 2016 bee data. This row contains the Start Time of the survey. We need to deal with this somehow. Here are some options with my comments.

- Remove the initial row

I dislike this option because we are losing information that may be important in the future.

- Create a new file storage structure that puts hour and minutes as part of the directory name

We already have years, months, and days, so make hours and minutes would be consistent. We could write a script to move the data for us. 

- Write a script that ignores the first row

Now the data in the R package won't have the time, but the time is still in the real data and we can create a script in the future that extracts the time if needed.

- Write a script that also extracts the time.

I'm not sure we need to do this now.

**Comment by sethapp** [comment]
Thanks for catching this. I don't want to remove the initial row. I would prefer to not include hour and minutes as part of the directory name. I'm in favor of a script that ignores the first row and then we can use it in the future if needed.

**Comment by sethapp** [comment]
I added the start time as the first line to all 2016 data. We have chosen the option "Write a new script that ignores the first row"
