### ISSUE TITLE
Order variables

### ISSUE THREAD

**Issue by jarad** [jarad/ISUmonarch#50]
In `data.frame`s order columns in this ordering: year, month, day, siteID, transectID, round, section. Then add additional variables.

**Comment by nulloa** [comment]
Should the variable `section` be named `section` or `distance`? I am seeing both in the data. 

Also `environment`, `monarch` don't have a `section` or `distance` variable. Do I just order the other variables they do have accordingly?

@sethapp

**Comment by sethapp** [comment]
The section/distance discussion is in issue #46 and it should always be section.

And to the second question yes I think so

**Comment by nulloa** [comment]
Right thanks!

**Comment by nulloa** [comment]
All the datasets are in a consistent order.
