### ISSUE TITLE
keep recorder variable in landscape2016 dataset

### ISSUE THREAD

**Issue by nulloa** [jarad/ISUmonarch#52]
I noticed in the `landscape2016` dataset, the variable `recorder` is in it, but in the script, that variable is removed. Do you want to keep the variable or remove it?

@sethapp @jarad

**Comment by sethapp** [comment]
I believe we want to keep it but all 'recorder' variables should be renamed 'observer'. See closed issue #36

**Comment by nulloa** [comment]
Sounds good. We can always remove it down the road if we don't need it.
