### ISSUE TITLE
Transect Section Length Issues

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch#58]
As we have already discussed and is detailed in https://github.com/jarad/ISUmonarch/blob/master/data-raw/survey/2016/survey2016.csv some 'section_length' in 2016 are 10m and some are 20m. 
On sites which used section_length of 20m, the final 'section_length' was 10m for sites that did not have a 'length' divisible by 20 (sites for which 'length' was 30, 50, or 70m). For example the header would say 0-20m,20-40m,40-50m. Has this been compensated for in the script?

**Comment by jarad** [comment]
Right now the script just reads in the header from the data files. So if the header has 40-50m, the data.frame has this value. So I believe the answer is yes. But did you mean something else?

**Comment by sethapp** [comment]
I just wanted to make sure this was accounted for. No, I wasn't referring to anything else.
