### ISSUE TITLE
tver1a_3 2016 Strange Header

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch#59]
This survey has a very strange header and I want to make sure the script can account for it. This is how the data was collected.

https://github.com/jarad/ISUmonarch/blob/master/data-raw/nectar/2016/08/12/JaclynA/ver1_tver1a_3.csv

0-20m	20-40m	40-50m	50-70m	70-90m	90-100m

**Comment by nulloa** [comment]
Looks good to me:
![image](https://user-images.githubusercontent.com/5848093/52917814-3e778380-32b5-11e9-8a75-907081e5cc75.png)

Here's the code I ran:
```
library(ISUmonarch)
library(dplyr)
nectar %>% filter(year=="2016" & month=="08" & day=="12" & siteID=="ver1")
```

Let me know if something looks off.
