### ISSUE TITLE
Create help files for new data.frames

### ISSUE THREAD

**Issue by nulloa** [jarad/ISUmonarch#62]
There are four new data.frames that need help files:
- species - just a pure read-in of `nectar_species_scientific_name_counting_unit.txt`
- ramet - can basically copy the nectar help file and modify
- survey - contains survey metadata
- transect - just connects transects and sites

Some code to see what is in each data.frame:
```
library(ISUmonarch)
head(species)
head(ramet)
head(survey)
head(transect)
```

**Comment by nulloa** [comment]
Since `daubenmire` got replaced with three new data.frames, they will also need R help files:
`cover`, `litter`, `milkweed`

**Comment by nulloa** [comment]
Need to create new/unpdate helpfile for `transect`, `site`, and `landcover`

**Comment by nulloa** [comment]
Update `robel` helpfiles to include new information from #70 


Part of which is: `censored` data with options `not` and `right` depending on if obs is greater than 16.

**Comment by sethapp** [comment]
Done
