### ISSUE TITLE
create data.frame for 'site_details'

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch#67]
This csv https://github.com/jarad/ISUmonarch/blob/master/data-raw/transect/site_details.csv
contains site_details which can be used to build a corresponding data.frame. 

Contains site (aka plot) specific details related to 2016 (before site preparation) vegetation and management, site preparation details, and soils information.

After it is created, create an issue for me to add a helpfile.

@nulloa

**Comment by nulloa** [comment]
If I understand correctly, you wanted a data.frame from the csv? if so, it was completed in 8330666b4219cd1ab1934897b1c5adad8c041abc
