### ISSUE TITLE
Fix Robel Data

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch#70]
@jarad @nulloa 

I learned today that robel pole measurements (aka Visual Obstruction Readings) are not standard and vary across ecological regions (i.e. tallgrass prairie vs shortgrass prairie). Although there are other minor variables in how this data is collected, the major variable is the length of band for the pole. The first picture shows a pole that looks like ours (bands are 10cm long and numbering begins with 1 as the first band), while the second picture shows another version with much smaller bands.

![image](https://user-images.githubusercontent.com/22353630/54780320-6d03b980-4be7-11e9-949d-d67415c12362.png)
![image](https://user-images.githubusercontent.com/22353630/54780384-93c1f000-4be7-11e9-8352-8f88616c8452.png)

The pole we used (10cm bands) appears to be the original pole design. From what I can find in the literature, robel pole measurements are not reported in a standard fashion. They always explain the pole and band design but sometimes they report their findings in number of bands and other times they convert the bands to the actual length it represents. Some researchers use bands based on the metric system while others use the standard system.

With all that said- I think we should convert robel pole readings to actual length in cm as anyone can understand lengths (as opposed to bands). I'm assuming this will be easy to do because it is simply the band number *10. The numbers below indicate the height at the top of the band in cm.

Robel reading (current data): actual height in cm (proposed data)
0: 0cm
1: 10cm
2: 20cm
3: 30cm
...
16: 160cm

Also, some data was entered at >16. This is correct. The vegetation was taller than the pole. I'm not sure what we do about this data.

**Comment by nulloa** [comment]
This is done. I think the best practice for those above 16 is to mention it in the analysis, the helpfile and the readme. Just mention that these are really estimates? rather than measurements. @jarad what do you think? Either way, I'll complete the change and update the data.frame.

**Comment by jarad** [comment]
For statistical analysis censored data is usually represented using two columns, e.g. height and censored. Height is either the actual height measured or the censoring value. Censored indicates whether the observation was censored and, if relevant, what type of censoring there is. 

We could do this, but at a minimum I think we should change >16 to >160.

**Comment by nulloa** [comment]
Add `censored` data with options `not` and `right` depending on if obs is greater than 16.
