### ISSUE TITLE
Update survey dataset to new transect name structure

### ISSUE THREAD

**Issue by nulloa** [jarad/ISUmonarch#71]
I need to update the survey data.frame with the new transect name structure. Should I be changing the csv files directly? or just in the data.frame? 

For the other data.sets we changed the csv names bit in this case I'll need to change the names inside the csv files. What is the best approach?

**Comment by sethapp** [comment]
I'm not sure I understand. If the csv's have already been changed then I would think you would only need to change the data.frame but if the csv's are still in the old format then I think changing the csv files would be the way to go because that's what we did before.

**Comment by nulloa** [comment]
I decided to change the files directly. In the other cases the datasets got their transect info from the file name but not in the survey datasets. I changed it. We can always revert back if we want.
