### ISSUE TITLE
Incorporate 2019 data to datasets

### ISSUE THREAD

**Issue by nulloa** [jarad/ISUmonarch#74]
Round 1 and 2 for 2019 are about to be added/are added so we need to add them to the datasets/test for conformity to csv standards.

**Comment by nulloa** [comment]
Errors with:
 - daubenmire
 - robel

To fix we need pdfs.

**Comment by nulloa** [comment]
Done for rounds 1 and 2 of 2019. 69e70458103bf98b15d863c4c2675769e2ed861d

**Comment by jarad** [comment]
I believe we are just waiting for round 3 data.

**Comment by jarad** [comment]
Now I just need to rebuild the R package
