### ISSUE TITLE
2019 Survey csv

### ISSUE THREAD

**Issue by nulloa** [jarad/ISUmonarch#75]
Did the survey details change from 2019 to 2018?

If its the same as 2018, let me know and I can make a copy.

Otherwise @sethapp can you add the `survey2019.csv` to the repo?

**Comment by sethapp** [comment]
2019 is the same as 2018. You can make a copy.

**Comment by nulloa** [comment]
This has been done in 9e73f218296a77c88bdf8f5756776399821bd0ad
