### ISSUE TITLE
Filling in Missing Data

### ISSUE THREAD

**Issue by nulloa** [jarad/ISUmonarch#76]
@sethapp when filling in missing values should we fill in with 0 or NA?

For example in `daubenmire/2019/06/17/NickO/gro1_tgro1a_1.csv2 ` looks like this:
```
"Direction",0m,10m,20m,30m,40m,50m,60m,70m,80m,90m
“n”,16,11,11,12,10,8
“e”,7,10,7,7,6,6
“s”,7,11,8,8,8,5
“w”,5,7,7,6,8,7
```

The pdf shows this:
![image](https://user-images.githubusercontent.com/5848093/61539166-88010180-aa00-11e9-9b6b-b2bf6e6c80d0.png)

Should it be changed to:
```
"Direction",0m,10m,20m,30m,40m,50m,60m,70m,80m,90m
“n”,16,11,11,12,10,8,0,0,0,0
“e”,7,10,7,7,6,6,0,0,0,0
“s”,7,11,8,8,8,5,0,0,0,0
“w”,5,7,7,6,8,7,0,0,0,0
```
or
```
"Direction",0m,10m,20m,30m,40m,50m,60m,70m,80m,90m
“n”,16,11,11,12,10,8,NA,NA,NA,NA
“e”,7,10,7,7,6,6,NA,NA,NA,NA
“s”,7,11,8,8,8,5,NA,NA,NA,NA
“w”,5,7,7,6,8,7,NA,NA,NA,NA
```

I was thinking 0 but wanted to be sure first

**Comment by sethapp** [comment]
This is actually what it should say. There are no zeros, NAs, or missing values. The transect is only 60m long so the header should have been shortened. 

"Direction",0m,10m,20m,30m,40m,50m
“n”,16,11,11,12,10,8
“e”,7,10,7,7,6,6
“s”,7,11,8,8,8,5
“w”,5,7,7,6,8,7

**Comment by nulloa** [comment]
Perfect. Thanks!

In general, is there a way to know if it's 0s or simply should be shortened?

**Comment by sethapp** [comment]
If you see a large consistent chunk of potentially missing data I would go check the survey.rda to see what the transect length was. Remember that the final line of the header will be 10m less than the length of the transect, i.e. a 60m transect takes data from 0-50m but not at 60m; it will have 6 values.

**Comment by nulloa** [comment]
Ahhh good point. I'll do that. Thanks! Hoping to get everything done later today and I'll get to your email.
