### ISSUE TITLE
2017 bee data includes additional row

### ISSUE THREAD

**Issue by jarad** [jarad/ISUmonarch#8]
The 2017 bee data includes a row with the start time but the 2016 data does not. Thus script to read in the bee data fails due to a difference in how the data are stored.

**Comment by sethapp** [comment]
2016 data sheet does not have start time on it but we do have the data. The start time is the same as the 2016 'monarch' data. My thought is that I will add the start time to the first line of each of the 2016 bee data. Do you agree?

**Comment by jarad** [comment]
Sounds good.

**Comment by sethapp** [comment]
Additional first line has been added to all 2016 bee data
