### ISSUE TITLE
Nectar Species Documents: do they match?

### ISSUE THREAD

**Issue by sethapp** [jarad/ISUmonarch#80]
This document is up to date. https://github.com/jarad/ISUmonarch/blob/master/data-raw/nectar/nectar_species_scientific_name_counting_unit.txt

I am not sure if this dataset is as we haven't been manually updating it. https://github.com/jarad/ISUmonarch/blob/master/data/species.rda 
It should completely match the first document.

**Comment by jarad** [comment]
I re-ran [species.R](https://github.com/jarad/ISUmonarch/blob/master/data-raw/species.R) and the [species.rda](https://github.com/jarad/ISUmonarch/blob/master/data/species.rda) file didn't change. So I believe the data.frame is up to date as of commit 35b34a0
