### ISSUE TITLE
na exists in Site Metadata Git 4-7-17.xlsx

### ISSUE THREAD

**Issue by jarad** [jarad/ISUmonarch#9]
The file [Site Metadata Git 4-7-17.xlsx](https://github.com/jarad/ISUmonarch/blob/master/data-raw/Site%20Metadata%20Git%204-7-17.xlsx) uses "na" for not available (?) and therefore causes issues when converting to numeric. I suggest we just leave the cell blank. This causes a warning in [length.csv script](https://github.com/jarad/ISUmonarch/blob/master/data-raw/length.R) when it attempts to enforce numeric lengths.

**Comment by jarad** [comment]
Probably find-replace "na" with "NA" will fix this.

**Comment by sethapp** [comment]
I did this. I'm not sure if it fixed it. When I try to run it under the run_all.R script I get this
> source("length.R")
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'length.R': No such file or directory

**Comment by jarad** [comment]
I believe you weren't in the data-raw/ folder when you tried to run this. Nonetheless, it did not fix the problem.
